### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by SeekPoint** [flrngel/TagSpace-tensorflow#1]
mldl@mldlUB1604:~/ub16_prj/TagSpace-tensorflow$ python train.py
  File "train.py", line 66
    result = sess.run(train_opts, feed_dict={f'{model.__class__.__name__}/doc:0': batch_input, f'{model.__class__.__name__}/tag_flag:0': batch_tags, f'{model.__class__.__name__}/lr:0': [lr]})
                                                                               ^
SyntaxError: invalid syntax
mldl@mldlUB1604:~/ub16_prj/TagSpace-tensorflow$

**Comment by flrngel** [comment]
using python3.6 will resolve this issue

**Comment by SeekPoint** [comment]
it also fails on python3.5.2
however, since it hard to update python3 on my workstation, do you have any idea to to make it compatible with python3.5?

thanks

**Comment by flrngel** [comment]
@loveJasmine just change code `print(f'variable asdf: {asdf}')` as below,
```
print("variable asdf: " + asdf)
```
